mode: immediate
silent: false
branchName: full
autoLinkIssue: true
autoCloseIssue: true
autoDeleteBranch: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueProjectsToPR: true
copyIssueMilestoneToPR: true
gitSafeReplacementChar: "-"
branches:
  - label: bug
    prefix: bugfix/
    skip: false
  - label: enhancement
    prefix: feature/
    skip: false
  - label: '*'
    skip: true
