mode: immediate
silent: false
branchName: full
autoLinkIssue: true
autoCloseIssue: true
autoDeleteBranch: true
gitSafeReplacementChar: "-"
branches:
  - label: bug
    prefix: feature/
    skip: false
  - label: enhancement
    prefix: bugfix/
    skip: false
  - label: '*'
    skip: true
