mode: immediate
silent: false
branchName: full
gitSafeReplacementChar: "-"
autoLinkIssue: true
autoCloseIssue: true
autoDeleteBranch: true
defaultBranch: develop
branches:
  - label: bug
    prefix: bugfix/
    skip: false
  - label: enhancement
    prefix: feature/
    skip: false
  - label: '*'
    skip: true
