mode: immediate
silent: false
branchName: full
autoLinkIssue: true
autoCloseIssue: true
autoDeleteBranch: true
copyIssueDescriptionToPR: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
gitSafeReplacementChar: "-"
branches:
  - label: bug
    prefix: bugfix/
    prTarget: main
    skip: false
  - label: enhancement
    prefix: feature/
    prTaget: main
    skip: false
  - label: '*'
    skip: true
