name: Create Branch on Issue Open

on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened]

jobs:
  create_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Create branch for issue
      uses: robvanderleek/create-issue-branch@main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
